-- CREATION DE LA BASE DE DONNEES SAMA_ECOLE

CREATE DATABASE SAMA_ECOLE;

-- UTILISATION DE LA BASE DE DONNEES SAMA_ECOLE

USE SAMA_ECOLE;

-- CREATION DE LA TABLE Ecole         

CREATE TABLE ECOLE(
	EcoleID INT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL, 
	adresse  VARCHAR(100) NOT NULL, 
	email VARCHAR(30) UNIQUE NOT NULL,
	telephone VARCHAR(20) UNIQUE NOT NULL
);

-- CREATION DE LA TABLE STATUT 

CREATE TABLE STATUT (StatutID INT  PRIMARY KEY, 
poste VARCHAR(30) NOT NULL, 
categorie VARCHAR(30) NOT NULL
); 

-- pour afficher la structure d'une table on exécute la commande suivante :
EXEC sp_columns STATUT;

-- CREATION DE LA TABLE PERSONNEL

CREATE TABLE PERSONNEL ( PersonnelID INT PRIMARY KEY, 
nom VARCHAR(30) NOT NULL ,
prenom VARCHAR(30) NOT NULL, 
adresse VARCHAR(50) NOT NULL,
sexe VARCHAR(20) NOT NULL, 
telephone VARCHAR(30) UNIQUE NOT NULL, 
email VARCHAR(30) UNIQUE NOT NULL

/*
 EcoleID INT,
 StatutID INT,
    CONSTRAINT fk_ecole_id FOREIGN KEY (EcoleID) REFERENCES ECOLE(EcoleID),
    CONSTRAINT fk_statut_id FOREIGN KEY (StatutID) REFERENCES STATUT(StatutID)
	*/
); 

ALTER TABLE PERSONNEL 
	ADD EcoleID INT;

ALTER TABLE PERSONNEL
	ADD StatutID INT;

ALTER TABLE PERSONNEL
	ADD CONSTRAINT fk_ecole_id FOREIGN KEY (EcoleID) REFERENCES ECOLE(EcoleID);
ALTER TABLE PERSONNEL
	ADD CONSTRAINT fk_statut_id FOREIGN KEY (StatutID) REFERENCES STATUT(StatutID);

-- CREATION DE LA TABLE ELEVE
CREATE TABLE ELEVE (
	EleveID INT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL,
	prenom VARCHAR(50) NOT NULL,
	date_naissance DATE NOT NULL,
	sexe VARCHAR(30) NOT NULL,
	adresse VARCHAR(30) NOT NULL,
	telephone VARCHAR(30) UNIQUE NOT NULL,
	email VARCHAR(30) UNIQUE NOT NULL
);

-- CREATION DE LA TABLE ANNEE_SCOLAIRE

CREATE TABLE ANNEE_SCOLAIRE(
	 Annee_scolaireID INT PRIMARY KEY,
	 ANNEE VARCHAR(9) NOT NULL
);

CREATE TABLE NIVEAU (
	NiveauID INT PRIMARY KEY,
	libelle VARCHAR(30) NOT NULL
);

EXEC sp_columns NIVEAU;

CREATE TABLE MATIERE (
	MatiereID int PRIMARY KEY,
	libelle VARCHAR(30) NOT NULL
);



/*
la clé étrangère coef_matiere des quatre tables 
Coef_MatiereID INT FOREIGN  KEY REFERENCES (Matiere,Niveau,Serie,Coefficient)(MatiereID, Niveau,Serie,Coefficient)
*/